# Generated by Django 4.0.1 on 2022-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exiftool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=20),
        ),
    ]
